# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d6c3314969f3e1bbc814aaa1f5353e62e2b3bd8f7184e6b35708f9208cbda0673a254f3e91f3aa9134b4de04e16fc65ea092ae762503068776b7cfc56d3649fe

test:
  secret_key_base: 26af8eeadd534afde4d7ce9c71a7c4576ee0bf3f426b2716bb3cd80de0b771c6050b44e6ca61c9c397d8cf5bf63985a392df01787b7ff5428fc6e1b3237773a7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
